### ISSUE TITLE
A failure occured in build()

### ISSUE THREAD

**Issue by AciDev** [linuxmint/slick-greeter#133]
```
 Arch based operating system
 ```

My issue is that when i try to install lightdm-slick-greeter through either makepkg -si or yay -S lightdm-slick-greeter. Everything seems to work fine until i get to a the .vala files then i get a string of warnings and 3 errors below will be the code which i hope can be useful in solving this.

menubar.vala:30.9-30.54: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
        public abstract ObjectPath[] enumerate_devices() throws IOError;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
menubar.vala:350.30-350.42: warning: Posix.SIGTERM has been deprecated since vala-0.40. Use Posix.Signal.TERM
shutdown-dialog.vala:561.13-561.27: warning: Gtk.Widget.override_font has been deprecated since 3.16
shutdown-dialog.vala:562.13-562.28: warning: Gtk.Widget.override_color has been deprecated since 3.16
shutdown-dialog.vala:563.13-563.28: warning: Gtk.Widget.override_color has been deprecated since 3.16
shutdown-dialog.vala:564.13-564.28: warning: Gtk.Widget.override_color has been deprecated since 3.16
shutdown-dialog.vala:84.9-84.24: warning: Gtk.Widget.margin_left has been deprecated since 3.12
warning: Gtk.Widget.margin_left has been deprecated since 3.12
shutdown-dialog.vala:85.9-85.25: warning: Gtk.Widget.margin_right has been deprecated since 3.12
warning: Gtk.Widget.margin_right has been deprecated since 3.12
shutdown-dialog.vala:107.13-107.37: warning: Gtk.Widget.override_font has been deprecated since 3.16
shutdown-dialog.vala:108.13-108.38: warning: Gtk.Widget.override_color has been deprecated since 3.16
shutdown-dialog.vala:141.9-141.27: warning: Gtk.Widget.override_font has been deprecated since 3.16
shutdown-dialog.vala:142.9-142.28: warning: Gtk.Widget.override_color has been deprecated since 3.16
menubar.vala:477.9-477.28: warning: Gtk.Widget.override_color has been deprecated since 3.16
menubar.vala:152.13-152.38: warning: Gtk.Widget.override_color has been deprecated since 3.16
menubar.vala:175.13-175.38: warning: Gtk.Widget.override_color has been deprecated since 3.16
menubar.vala:215.13-215.32: warning: Gtk.Widget.override_color has been deprecated since 3.16
prompt-box.vala:178.9-178.32: warning: Gtk.Widget.override_font has been deprecated since 3.16
prompt-box.vala:179.9-179.33: warning: Gtk.Widget.override_color has been deprecated since 3.16
prompt-box.vala:184.9-184.30: warning: Gtk.Widget.margin_left has been deprecated since 3.12
prompt-box.vala:199.25-199.37: warning: Gtk.Alignment has been deprecated since 3.14
prompt-box.vala:234.9-234.38: warning: Gtk.Widget.override_font has been deprecated since 3.16
prompt-box.vala:235.9-235.39: warning: Gtk.Widget.override_color has been deprecated since 3.16
prompt-box.vala:238.9-238.36: warning: Gtk.Widget.margin_left has been deprecated since 3.12
prompt-box.vala:246.25-246.37: warning: Gtk.Alignment has been deprecated since 3.14
dash-entry.vala:74.9-74.21: warning: Gtk.Widget.override_font has been deprecated since 3.16
prompt-box.vala:455.9-455.27: warning: Gtk.Widget.override_font has been deprecated since 3.16
prompt-box.vala:460.9-460.28: warning: Gtk.Widget.override_color has been deprecated since 3.16
prompt-box.vala:533.9-533.40: warning: Gtk.Widget.override_font has been deprecated since 3.16
greeter-list.vala:42.5-42.34: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public string get_active_entry ()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
greeter-list.vala:52.5-52.32: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void set_active_entry (string entry_name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
slick-greeter.vala:324.9-324.40: warning: unhandled error `GLib.Error'
        greeter.cancel_authentication ();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
slick-greeter.vala:309.9-309.37: warning: unhandled error `GLib.Error'
        greeter.authenticate (userid);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
slick-greeter.vala:314.9-314.40: warning: unhandled error `GLib.Error'
        greeter.authenticate_as_guest ();
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
list-stack.vala:75.34-75.61: error: Assignment: Cannot convert from `GLib.List<weak Gtk.Widget>' to `GLib.List<Gtk.Widget>?'
        unowned List<Gtk.Widget> prev = children.last ().prev;
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
list-stack.vala:76.13-76.16: error: The name `prev' does not exist in the context of `ListStack.pop'
        if (prev != null)
            ^^^^
list-stack.vala:77.14-77.17: error: The name `prev' does not exist in the context of `ListStack.pop'
            (prev.data as GreeterList).greeter_box.pop ();
             ^^^^
main-window.vala:193.13-193.28: warning: Gtk.Widget.margin_left has been deprecated since 3.12
main-window.vala:194.13-194.29: warning: Gtk.Widget.margin_right has been deprecated since 3.12
main-window.vala:203.33-203.48: warning: Gdk.cairo_create has been deprecated since 3.22
remote-login-service.vala:46.5-46.42: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void get_servers (out RemoteServer[] serverList) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote-login-service.vala:47.5-47.52: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void get_servers_for_login (string url, string emailAddress, string password, bool allowCache, out bool loginSuccess, out string dataType, out RemoteServer[] serverList) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote-login-service.vala:48.5-48.60: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void get_cached_domains_for_server (string url, out string[] domains) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
remote-login-service.vala:49.5-49.51: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public abstract async void set_last_used_server (string uccsUrl, string serverUrl) throws IOError;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
slick-greeter.vala:329.9-329.34: warning: unhandled error `GLib.Error'
        greeter.respond (response);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
slick-greeter.vala:319.9-319.76: warning: unhandled error `GLib.Error'
        SlickGreeter.singleton.greeter.authenticate_remote (session, userid);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
main-window.vala:53.9-53.33: warning: Gtk.Widget.override_background_color has been deprecated since 3.16
main-window.vala:55.9-55.23: warning: Gtk.Window.has_resize_grip has been deprecated since 3.14
main-window.vala:68.29-68.41: warning: Gtk.Alignment has been deprecated since 3.14
main-window.vala:106.25-106.37: warning: Gtk.Alignment has been deprecated since 3.14
main-window.vala:124.21-124.33: warning: Gtk.Alignment has been deprecated since 3.14
slick-greeter.vala:736.5-736.20: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void open (uint32 type, uint32 timestamp, uint32 seconds_to_stay_open, ObjectPath[] inhibitor_object_paths)
    ^^^^^^^^^^^^^^^^
slick-greeter.vala:741.5-741.21: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void close ()
    ^^^^^^^^^^^^^^^^^
slick-greeter.vala:61.58-61.90: warning: unhandled error `GLib.Error'
        greeter.autologin_timer_expired.connect (() => { greeter.authenticate_autologin (); });
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
slick-greeter.vala:703.36-703.48: warning: Posix.SIGKILL has been deprecated since vala-0.40. Use Posix.Signal.KILL
Compilation failed: 3 error(s), 53 warning(s)
make[2]: *** [Makefile:1107: slick_greeter_vala.stamp] Error 1
make[2]: Leaving directory '/home/tom/.cache/yay/lightdm-slick-greeter/src/slick-greeter-1.2.4/src'
make[1]: *** [Makefile:403: all-recursive] Error 1
make[1]: Leaving directory '/home/tom/.cache/yay/lightdm-slick-greeter/src/slick-greeter-1.2.4'
make: *** [Makefile:342: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: lightdm-slick-greeter

**Comment by leigh123linux** [comment]
Fixed in git https://github.com/linuxmint/slick-greeter/commit/7f04f066a18b3f398f292846c4fc8cc837c678a3

**Comment by AciDev** [comment]
Sorry but im using the latest version to my knowledge and it is still not working

**Comment by AciDev** [comment]
the AUR might not have this fix

**Comment by leigh123linux** [comment]
That's AUR problem then, they will need to apply a patch to fix till the next release,
