### ISSUE TITLE
truncated password box

### ISSUE THREAD

**Issue by fossfreedom** [linuxmint/slick-greeter#33]
compiled and installed the v1.0.4 greeter released today.

This is the issue:

![untitled](https://cloud.githubusercontent.com/assets/996240/26361269/5b2f31e4-3fd2-11e7-90a9-165f7641fbae.png)

I can click the switch session icon and then the back button and the password box is then displayed correctly

Thoughts?

Ubuntu Budgie 17.04 - GTK+ 3.22

EDIT: 1.0.3 works just fine.

**Comment by fossfreedom** [comment]
fixed in v1.0.5.  Thanks.

**Comment by SamBurgos** [comment]
I just installed 1.0.5 in Archlinux, the problem still persists there 

![virtualbox_arch dev_29_05_2017_12_14_42](https://cloud.githubusercontent.com/assets/1509924/26558912/6304f606-4469-11e7-8b72-e0ffaea74c9f.png)

Archlinux with GTK 3.24 (in Arch 3.24 is 3.22 plus some additional patches, I dont know if I can provide something else

**Comment by clefebvre** [comment]
@SamBurgos does this help? https://github.com/linuxmint/slick-greeter/commit/77d8a4beac62c8666ce2cae513bd2ec6b19dc311

**Comment by SamBurgos** [comment]
![virtualbox_arch dev_30_05_2017_08_55_46](https://cloud.githubusercontent.com/assets/1509924/26589770/1d82562a-4516-11e7-9457-adb89ddd8c9f.png)

@clefebvre Yes, that commit and the new version on Github helped really great! I just updated the package on Arch so if anyone is having troubles there they can just upgrade as well. Thank you very much
